### ISSUE TITLE
Dead corner option not working

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#3443]
**Imported issue:**

* Author: Steven Dick
* Date: 2013-02-13 15:10:32
* Legacy ID: 3513

**Steps to reproduce:**

Configure server -> advanced server settings -> dead corners (cheboxes)

Checking these options changes things in the options section, but dead corners doesn't seem to do anything there.

Expected: This should either do something or the options should not be on this screen.

Actual: Dead corners works fine if you set it by double clicking on the individual screens, but not on the advanced server options pannel.

**Versions and operating systems:**

Version 1.4.10

**Comment by ErdnussFlipS** [comment]
Was is fixed?

In version 1.7.5 I get the same behaviour.

**Comment by joelmdev** [comment]
Is there a workaround for this?

**Comment by claell** [comment]
I thought dead corners wouldn't work at all before I read this. Did not know one could double click the screens.

I'd really suggest to fix such easy issues like this. I mean, this takes almost no time compared to other issues needing much research and trial & error.

**Comment by gxgani** [comment]
It still seems to be broken. Any news?

**Comment by makedir** [comment]
is this a joke? I just bought the program and found it totally useless because of dead corners not working. I want for example never leave my server screen when I come with the mouse to the corners (just switch to client via hotkey), but I want to switch back from my client to the server. and then I found this bug report. still not fixed? seriously? the app is totally useless without this feature.
