### ISSUE TITLE
Fast cursor on any client with Mac server

### ISSUE THREAD

**Issue by nbolton** [synergy/synergy#451]
Keyword: accelerated cursor

**Imported issue:**

* Author: thatjunkaccount (Google user)
* Date: 2010-04-29 00:00:00
* Legacy ID: 461

> What list of steps will reproduce the problem?  
  
Running Synergy+ and moving the cursor from the Server screen to the Client screen  
  
> What version of operating system, and Synergy+ are you using?  
  
Server: Snow Leopard  
Client: Windows 7 Home Premium  
Synergy +: 1.3.5  
  
> What is the expected behaviour, and what happens instead?  
  
Normal mouse speed on the Server (Snow Leopard) is unusably fast on the Client (Windows 7).   
Slowing down the server mouse speed to the lowest setting makes the Client speed usable.   
Altering the mouse speed on the Client has no effect. I have also experienced the 'infinite   
acceleration' problem during FPS games on the Windows 7 Client.  
  
> Is there a way of temporarily working around your problem?  
  
Turning down the Server mouse speed solves the client-too-fast-to-use problem, but generates   
a server-too-slow-to-be-practical  
  
> Would you like to solve the problem yourself and submit a patch?  
  
I have no experience in coding, or applying patches

**Comment by JoshMcCullough** [comment]
Note that if I hit `ScrLk` on my Win8.1 client (Win7 server), the mouse cursor speed doubles (roughly). It's not just an OSX issue.

**Comment by robnasby** [comment]
Glad to see this is moving up the priority list.  Thanks!

**Comment by zeroasterisk** [comment]
Same problem:

* Synergy : 1.6.3
* Server OS: 10.10.2
* Server Machine: MacBook Pro 17" Early 2011 @ 1920x1200 
 * with a second HDMI display @ 1920x1080
 * fresh OS / Synergy install
* Client Machine: Ubuntu 14.04 64-bit running DVI display @ 1680x1050 (highest)
 * pointer speed on slowest setting
 * fresh OS / Synergy install

Cursor just zooms around when on client... working great otherwise.

**Comment by SynVisions** [comment]
+1 on this, have to restart my OS X Synergy server on a regular basis to fix.

Thanks

**Comment by rogerdrummond** [comment]
FYI- The Client (Win8.1) does NOT have to even be powered on to create this behavior using a Mac Server.  

For verification:
* I started Synergy on the MacbookPro Client (Yosemite), and slid over to the Win8.1 desktop (mouse performed normally). 
* Turned all machines OFF except the Mac (i.e. I powered down the Win8.1 machine).
* Picked "Sleep" from the Apple dropdown Menu.  Waited 5 seconds. Clicked mouse to wake up.
* Repeated "Sleep"/Wakeup cycle 7 times. (Took about 1 minutes total, roughly 10 seconds each).
* Plugged in Win8.1 machine and powered on.
* Slid mouse over to Win8.1 desktop to login, but mouse was moving too fast to control. (The same cumulated speed that normally develops with 7 sleep cycles).

Thank you for prioritizing this bug Nick. I know it's in the best interest of Synergy to fix it, but since using a Synergy/Win server is very buggy for programming in Xcode (especially scroll wheel functions), I have no choice but to use the Synergy/Mac server, and this bug has been a fundamental roadblock in continuing to use your software.

I should note that my mac uses SSD and no longer hibernates to disk during sleep, which may impact your own sleep cycle during testing. However, I can also replicate this behavior by immediately clicking the mouse to wakeup within a second of clicking the Sleep dropdown, so it does not seem to have to fully go to sleep.  I’ll also note that I am hardwired to the router on both machines, though that should also have no impact since the bug shows up without having any other machines on the network. 

This thread appears to have multiple issues described, and they likely interact or get confused due to random sleeping.  The 'fundamental' bug appears to behave the way my apps behave when I set an "event notification" every time I wake up, but forget to remove the "notification" before going to sleep.  The notifications become cumulative.

**Comment by focs** [comment]
Same problem here. Restarting the server seems to solve the problem.

**Comment by leothelocust** [comment]
Same here. Restart server and mouse moves as expected.   The second I lock/unlock my mac, mouse is super slow on my mac, and super fast on my windows client.

**Comment by mike-lischke** [comment]
Wow, so many affected people and still no solution in sight? Just want to bump the issue, I'm also affected by this (latest synergy server on Mac Yosemite, Win 8.1 client). Problem appeares when the Win machine wakes up. Restarting the synergy server solves this temporarily.

**Comment by reversefold** [comment]
I'm having this kind of issue going from one 15" Retina MacBook Pro to another 15" Retina MacBook Pro so it's not necessarily specific to the client's PPI.

**Comment by speaker** [comment]
@kahiroka,

That fix looks very interesting, can you elaborate on it?

**Comment by kahiroka** [comment]
Hi @speaker,
This issue is caused by multiple registration of a callback function which is used to capture input events. That workaround is intended for fixing it. I have been using the workaround for a while, it seems to work well.

**Comment by JoshMcCullough** [comment]
This isn't just an issue w/a Mac server, FYI. I have the same issue (as indicated above in this thread) with a Win7 server and Win8.1 client. If I ScrLk while on the client, the mouse cursor becomes roughly twice as fast as it should be.

**Comment by jacklink01** [comment]
So I don't mean to be rude, but was this issue which has existed for years just fixed by adding literally one line of code...... ONE LINE?!

**Comment by mike-lischke** [comment]
@jacklink01 not so surprising, this is how it often goes in software development. The key in such cases is not the actual fix but to find out what's wrong and what it needs to be fixed.

**Comment by jacklink01** [comment]
I get it. I guess I'm just surprised because this bug has existed for as long as synergy has existed and has actually been the only bug I've ever experienced with synergy on a regular basis. I just can't believe it took this long. So glad it's fixed though

**Comment by zeroasterisk** [comment]
Don't be fooled.... I've seen a single punctuation mark change be the culmination of months of effort for a team of developers... There are often a lot of low hanging fruit and easy wins... and there are often many more hard to find solutions for elusive or difficult to determine problems.  Unless you're doing the work, it's often difficult to determine.

**Comment by JoshMcCullough** [comment]
@jacklink01 It's not fixed completely, because the issue exists on non-OSX setups as well. @nbolton

**Comment by kahiroka** [comment]
@JoshMcCullough Does the issue you are facing occur when (1) 'Use relative mouse moves' mode is checked, (2) pointer speed in control panel on a client side is set to faster rather than neutral and (3) 'Locking cursor to screen' functionality is used?
If so, it is because mouse speed under the mode is strongly affected by acceleration setting on the client side that the speed becomes faster than normal (absolute coordinates) mode. The easiest solution is to set the pointer speed to neutral or to uncheck the mode if you doesn't need it. Otherwise I think it would be better to reopen #3950 issue for further discussion.

**Comment by visbits** [comment]
Running OSX 10.10.3 Yosemite as server and Win 7 Pro as client.

Issue persist only when clicking a window.   Mouse moves normal but once you click and hold a window the scaling is crazy.    

I have a 5k imac and I'm wondering of the scaled OSX resolution emulates different mouse speeds?

**Comment by kahiroka** [comment]
@visbits I could reproduce a similar issue by pressing middle or side buttons on my mouse. (New MacBook/10.10.4/5 buttons BT mouse as server, Win 7 Pro as client) The cause of the issue is that onMouseMove() is doubly called at two locations, where are OSXScreen::handleDrag() and OSXScreen::handleCGInputEvent(), in case of a condition. It may depend on mouse device.

**Comment by twig** [comment]
Similar issue (mac 10.10 server, win7 pro x64 client).

Cursor on windows is intermittedly laggy and catches up at times. it's still usable but irritating.

**Comment by kahiroka** [comment]
I think it would be better to classify these types of issues related to mouse speed.
- Issue to be handled:
  - Mouse speed issue on client side
  - OS X as server, any client
- Occurrence Condition
  - Suspend/resume:
    I think this case is resolved at 1.7.4-stable(nightly builds) or later.
    Related issue: #4655 
  - Relative mouse moves is enabled:
    This causes an architectural problem in some cases.
    Try to uncheck relative mouse moves on synergy server or set mouse acceleration to neutral on client OS setting.
  - Mouse dragging (not trackpad):
    I wrote a clue to the issue above. More information is needed, for instance, mouse model name, type of generated event and so on.
    Related issue: #4471 (root cause may be the same as this.)
  - VMware issue above:
    It seems this issue is conflict with application which hooks cursor events. May be OS independent issue.
  - Others:
    More detailed information is needed.

**Comment by lukaszp** [comment]
I have the same issue with SmoothMouse and found workaround, maybe it will help to solve this issue. When I use Trackpad buttons it is working correctly. But Trackpad pointer is not working correctly. My SmoothMouse config is only "Enable for mice" and "Like in Windows". The next clue is that turning off mouse in SmoothMouse causes Marking in every program I tried  to break in Mac, and make Synergy unable to work event after synergy restart in client and server, and mac restart was required to fix it all. This would suggest some buggy mouse/trackpad code in OSX or USB or any other mac hardware, which is not so unexpected, because I have been experiencing issues with mouse and external Displays it the past. Maybe external displays (I use two of them) adds up to the equation.

**Comment by lukaszp** [comment]
I found another workaround. I uninstalled SmoothMouse, decreased mouse speed to 0 in BetterTouchTools to 0, and increased Mac native mouse speed. Now overall acceleration model is OK for me, and marking works properly in client because Smooth mouse is uninstalled.

I suspect that some crashes are due to interference with ClipMenu app. Plan to test it and maybe switch to less invasive Clipboard Guru for tests.

**Comment by lukaszp** [comment]
Maybe it is a subject for another issue, but maybe it is related. Fast mouse switching between screens causes clients to crash with:

INFO: previous clipboard data has become invalid.

My workaround is to switch switch delay to 500ms.

**Comment by jroes** [comment]
Also experiencing this issue. Yosemite on server, Windows 8 on client. The 500ms switch delay setting workaround works for me, but I'd prefer not to have to use it because it takes away from the ... synergy ... :)

**Comment by A2K** [comment]
Why is this issue closed? Is there a solution? I am still experiencing the problem with latest nightly build.

**Comment by sheldon** [comment]
Hi

I think this bug shouldn't be closed, considering the tags added 10 days ago :)

Just a friendly reminder and a bump of another user experiencing the issue.

Cheers and thanks for the hard work on this awesome product!

**Comment by wfjackson3** [comment]
Also experiencing this issue.

**Comment by jpatomic96** [comment]
This is still an issue for me with an OSX 10.11 server and windows 10 client

**Comment by ErikSwan** [comment]
Also frustrated that this hasn't been fixed in over a year.

**Comment by ErikSwan** [comment]
I got so fed up with this I decided to figure out how to fix it myself. For those wishing to compile to verify, see the PR for some changes that need to be made to get Synergy to compile on 10.10+.

**Comment by sheldon** [comment]
@ErikSwan thanks so much for the code work, I'll verify this evening :+1:

**Comment by pvannuff** [comment]
Great work, Erik! I had this issue as well and they have just incorporated it in 1.7.6 RC2. :-)

**Comment by XinyuHou** [comment]
Please try this nightly which should have a fix for this issue.

http://synergy-project.org/nightly?filter=synergy-v1.7.6-rc2-a5acb08

**Comment by ErikSwan** [comment]
@XinyuHou The fix in the 1.7.6 branch is not the correct fix. Even though it will work, it will still cause a memory leak since the run loop retains the source. The run loop source should be removed from the run loop before it is released. Please see the commit I made for details.

**Comment by kayasoze** [comment]
On 1.8.1 I still have this issue, but only when Smoothmouse is installed on the server.  There may be multiple issues here.

**Comment by nbolton** [comment]
@sheldon Did it work for you? @ErikSwan and @kayasoze seem to suggest it's not fixed :(

**Comment by sheldon** [comment]
@nbolton sorry but I didn't get the chance to try it out, away from home at the moment where my windows pc is to test on. will keep you posted early Jan when I'm back.

**Comment by ErikSwan** [comment]
@nbolton, the fix in the 1.7.6 branch is *a* fix, but it is not the correct fix as I understand things. The fix in the 1.7.6 branch will cause a memory leak since the run loop source is not removed from the run loop, although this only becomes non-trivial if the computer goes to sleep and wakes a large number of times.

I've tested the 1.7.6 branch and functionally, it does fix the problem. See ba592ad95f7eb554176dec5d5970596ef1971228 for what I consider to be the correct fix.

**Comment by XinyuHou** [comment]
@ErikSwan 

I merged your change into this nightly. Please test it.

http://synergy-project.org/nightly?filter=v1.7.6-rc3-51705f7

**Comment by ErikSwan** [comment]
Thanks, will test tonight.

**Comment by 335** [comment]
I solved this problem by v1.7.6-rc3-51705f7.
Thanks.

Server : rMBP 13" OSX 10.11.2 v1.7.6-rc3-51705f7
Client : Windows 10 Pro x64 v1.8.0-beta-4ff3cdd

**Comment by ErikSwan** [comment]
The nightly does fix the problem, but I am also seeing this in the log upon sleep:

```ERROR: quartz event tap was disabled by user input```

It looks like some part of Synergy is having a problem with the event tap being removed from the run loop source. I'm not sure if this causes any problems with functionality or if it's just an extraneous error message. But it should probably be investigated before being merged into stable. Perhaps the other fix is better if this can't be tracked down, as the memory leak is trivial in practice.

**Comment by mengesb** [comment]
I tried version v1.7.6-rc3-51705f7 with a MacOSX server and an Ubuntu 14.04 LTS client, still having the mouse acceleration on click-hold/drag problem.

**Comment by XinyuHou** [comment]
@ErikSwan 
Thanks for the heads up.

I will investigate that.

**Comment by ErikSwan** [comment]
@mengesb I believe that is a different issue than the one being discussed here. This is solely related to consistent mouse acceleration due to the Mac server going to sleep and resuming.

**Comment by mengesb** [comment]
So my opened issue still stands? I'll reverify if the sleep/accelerate
problem still exists

**Comment by blakeman8192** [comment]
I am experiencing this issue with OSX server and Windows 10 client, both version 1.7.5.

**Comment by snazzware** [comment]
Posting this here in case somebody else w/ my issue comes searching - I have a similar issue, where mouse speed on the client becomes very fast. Restarting synergy seemed to resolve it, but it would come back after some short random interval. After experimentation, I found that my particular problem is triggered because I'm using VMware Fusion on the server. If I move the mouse cursor directly from a VMware Fusion window to a synergy client screen, I get crazy acceleration. If I first move the mouse out of vmware, and then move to the synergy client, all is well.

I don't blame Synergy for this scenario, but knowing the workaround makes me less likely to throw my macbook across the room :)

**Comment by rodentz** [comment]
I'm seeing it on OSX El Capitan (Client) and Ubuntu 14.04 (Server)

**Comment by opes** [comment]
Seeing the issue on Synergy 1.8.2-stable-36cd521

Server: Mac OS X El Capitan 10.11.6
Client: Windows 10 Pro

Notes: Mac server previously had SmoothMouse installed, but has since been removed and rebooted. The client is a fresh install of Windows 10. Tried rebooting, relative mouse move settings, and various other suggestions above. Issue goes away with Windows 10 as the server, Mac as the client.

**Comment by lambdaq** [comment]
Looks like SmoothMouse is the culprit?
