### ISSUE TITLE
Mapping problem with french keyboard

### ISSUE THREAD

**Issue by Karmak23** [synergy/synergy#4582]
Hi, here is my setup:

- server : Arch Linux 64Bit, Synergy version 1.7.1-2, GNOME 3.14, physical french keyboard with latin-9 "no-dead-keys" mapping.
- Client : Windows 7 professionnal 64Bit, Synergy version 1.7.1, physical french keyboard with default mapping, and language bar deactivated completely.

Description:

- When I type `Alt-Gr + 0` on server (with or without synergy running), I get an "`@`", which is the expected behaviour.
- Typing `Alt-Gr + 0` on client keyboard, I also get an `@`, which is also expected.
- When typing the same combination on server keyboard with client focused, I get an "`à`", which is like `Alt-Gr` was not held during typing. 

All other `Alt-gr` combinations don't work either, eg. `Alt-Gr` + `(` should produce "[" but produces "`(`", etc). 

Note: the `Shift-Alt_Gr` combinations don't work either (eg. `Shift-Alt_Gr-n` produces `→` and `Shift-Alt_Gr-n` the ellipsis `…` on server, but nothing at all on client). I think the `Shift-Alt_Gr` is a special case because it's specific to the latin-9+non_dead_keys variants (I don't even know how to type an ellipsis or a non-breakable space on a normal windows keyboard).

`Control`-based modification works correcty (eg. `Control` + `C` copies, `Control` + `V` pastes, and all other I could test produce the expected behaviour), and so do simple `Alt`-based combinations.

It seems the problem lies somewhere translating the `Alt-Gr` key from linux to windows (the problem was already the same with Ubuntu 12.04 server, windows 7 client and synergy 1.6 on both sides as far as I can remember).

Tell me if I can do anything to help debugging the issue. I would be very glad to type []@ from server to client because I use both machines for coding.

**Comment by speaker** [comment]
This looks to be the same issue as #4310, would you agree?

**Comment by Karmak23** [comment]
Yes I agree, but in #4310 there are 2 distinct problems reported:

- the same as here
- and auto-switching to EN keyboard when we use more than one.

In fact, I added “*and language bar deactivated completely*” because with 2 keyboards mappings on windows **client** (not server), the mapping was automatically changed to US, like described in #4310. But i narrowed the problem by disabling the language bar, because the not-working `Alt-Gr` is a much more important problem : the only way to work it around is to use the client keyboard again, which makes synergy totally useless. 

Thus I would prefer to keep this issue open and narrow the #4310 to the auto-switch mapping bug. but I won't mind if the current issue is closed as duplicate, as long as the `Alt-Gr` problem is not forgotten to be fixed ;-)

**Comment by speaker** [comment]
Happy to keep it open, we'll focus on the Alt-Gr problem here.

**Comment by Karmak23** [comment]
Tell me If I can do something (user-related) like installing a debug version and sending you detailled reports. I'm a developer thus I can dig quite deep, but have small time and don't know anything about keyboard mappings internals.

**Comment by vannitotaro** [comment]
Same problem for me, with an Italian keyboard, client Windows 10 Home 64-bit, server Ubuntu 15.10 32-bit. Could someone please **change the issue title to reference `Alt-Gr`** instead of French?

Some workarounds:

    ~   ALT+126
    #   ALT+35
    @   ALT+64
    `   ALT+96
    [   CTRL+ALT+[
    ]   CTRL+ALT+]
    €   CTRL+ALT+€

**Comment by OrganicBrian** [comment]
Karmak23 and vannitotaro, I noticed that this issue doesn't mention your make/model of keyboard or the language setting in each system's Synergy (in the GUI, in "Edit" -> "Settings"). Could we please get that info? Often, key mapping issues are solved by choosing a language compatible with the physical keyboard in both the OS settings and the Synergy settings.

**Comment by vannitotaro** [comment]
@OrganicBrian thank you for your interest in this issue. I just tried half your solution, but the problem is still there even if I change client, server or both Synergy settings from English to Italian (with both OSes in English with Italian layout - I would not switch to Italian for system language too, just to overcome this issue). About the keyboard, both client and server are running on laptops with integrated Italian-layout keyboard, and the problem is present even using USB keyboards, so I think make/model are probably not relevant here.
