### ISSUE TITLE
Can not copy unicode characters from server to client

### ISSUE THREAD

**Issue by ryansyah** [synergy/synergy#4973]
Hello,

I have just updated my server and client to 1.7.4.

FreeBSD 10.1 AMD64 as server, synergy installed from ports tree.
OSX Yosemite 10.10.4 macbook pro as client.

I had some unicode copy paste issues with server 1.7.3 that kept me from upgrading from 1.6.2, 1.7.4 seems to have (mostly) fixed the copy paste breakage, but now I am getting inconsistent copy/paste from server to client vs client to server.

With server on 1.6.2 and client on 1.7.3, I can copy the following unicode character back and forth from client to server and server to client without issue. Test unicode:
£¯

With server on 1.6.2 & client on 1.7.4, the client cannot connect to the server:

`[2015-08-18T14:08:39] NOTE: connecting to '10.X.X.X': 10.X.X.X:24800`

`[2015-08-18T14:08:39] WARNING: failed to connect to server: incompatible client 1.5`

With server on 1.7.3 & client on 1.7.3, copy/paste does not function at all.

With server on 1.7.4 and client on 1.7.4, I do not get the same resultant unicode when copying pasting from server to client, however limited testing seems to indicate that copy/paste from client to server is OK.

unicode in copy buffer of server:
£¯

what I get when I paste the above into client:
£ø

What I get when I paste the above back to my server from client copy buffer:
£ø

What I get when I paste the above back into my client from server copy buffer:
£¿

**Comment by icfr** [comment]
hello

i didn't test with other version but before registering i was on 1.4.3 and all was ok now on 1.7.4 
copy paste with some character don’t work or with Chinese character 

i dont know if it's the same problem but when there is problem with copy paste  server is dead and i must restart server and client

**Comment by ryansyah** [comment]
Hello,

I was submitting a new bug today for 1.7.5 (#5189) and decided to see how things were going with this unicode bug.

Current setup:
FreeBSD 10.2-RELEASE AMD64 as server, synergy 1.7.5 installed from ports tree.
OSX El Capitan 10.11.2 macbook pro as client, synergy 1.7.5

Test unicode:
£¯

Staring from client, copy test unicode and paste to server: PASS
Starting from server, copy test unicode and paste into client: PASS

Looks like this bug is now resolved.

**Comment by posita** [comment]
I'm pretty sure this needs to be reopened (possibly as a regression). I was just able to reproduce something similar: I copied an Emoji Unicode character on my client Mac (OS X 10.9, running Synergy 1.8.5-stable-a18eba7):

😔

When I switched screens to my server Mac (OS X 10.12, also running Synergy 1.8.5-stable-a18eba7), the text in the clipboard became:

�

Server log:

```
[2016-12-13T23:47:25] INFO: screen "<client>" grabbed clipboard 0 from "<client>"
[2016-12-13T23:47:25] INFO: screen "<client>" grabbed clipboard 1 from "<client>"
[2016-12-13T23:47:27] INFO: switch from "<client>" to "<server>" at 2452,780
[2016-12-13T23:47:27] INFO: entering screen
[2016-12-13T23:47:27] INFO: screen "<client>" updated clipboard 0
[2016-12-13T23:47:27] INFO: screen "<client>" updated clipboard 1
```

Client log:

```
[2016-12-13T23:47:27] INFO: leaving screen
[2016-12-13 T23:47:27] WARNING: cursor may not be visible
```

**Comment by posita** [comment]
I also verified that this still happens with 1.8.6-stable-2ab21aa.

**Comment by posita** [comment]
@Celant, can we reopen this?

**Comment by adamryczkowski** [comment]
The bug still is present in 1.8.8-stable-debian

**Comment by adamryczkowski** [comment]
...and on synergy version `1.10.3-stable, protocol version 1.6` downloaded from current github releases and compiled using libraries available in Ubuntu repository.
